name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        deno-version: [v2.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Lint
        run: deno lint
      - name: Format check
        run: deno fmt --check
      - name: Type check
        run: deno check mod.ts
      - name: Test
        run: deno test
        env:
          CI: true
      - name: Publish to JSR
        run: deno publish
